name: "TFC Deployment"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform CI/CD with TFC"
    runs-on: ubuntu-latest
    env:
      TF_CLOUD_ORG: ${{ secrets.TF_CLOUD_ORG }}                
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: "Initialize Terraform"
        run: terraform init

      - name: "Terraform Format Check"
        run: terraform fmt -check

      - name: "Terraform Validate"
        run: terraform validate

      - name: "Terraform Plan"
        run: terraform plan 

      - name: "Terraform Apply"
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
